version: '3.9'

services:
  backend:
    image: dasanlo5/aemet-test-backend:1.0.0
    container_name: aemet-backend
    ports:
      - "8080:8080"
    environment:
      AEMET_API_KEY: ${AEMET_API_KEY}
    restart: unless-stopped

  frontend:
    image: dasanlo5/aemet-test-frontend:1.0.0
    container_name: aemet-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
